set_property PACKAGE_PIN M11 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN F4       [get_ports dip_switch_4bits_tri_i[3]] ;# Bank  88 VCCO - VCC3V3   - IO_L9N_AD11N_88
set_property IOSTANDARD  LVCMOS33 [get_ports dip_switch_4bits_tri_i[3]] ;# Bank  88 VCCO - VCC3V3   - IO_L9N_AD11N_88
set_property PACKAGE_PIN F5       [get_ports dip_switch_4bits_tri_i[2]] ;# Bank  88 VCCO - VCC3V3   - IO_L9P_AD11P_88
set_property IOSTANDARD  LVCMOS33 [get_ports dip_switch_4bits_tri_i[2]] ;# Bank  88 VCCO - VCC3V3   - IO_L9P_AD11P_88
set_property PACKAGE_PIN D4       [get_ports dip_switch_4bits_tri_i[1]] ;# Bank  88 VCCO - VCC3V3   - IO_L8N_HDGC_88
set_property IOSTANDARD  LVCMOS33 [get_ports dip_switch_4bits_tri_i[1]] ;# Bank  88 VCCO - VCC3V3   - IO_L8N_HDGC_88
set_property PACKAGE_PIN E4       [get_ports dip_switch_4bits_tri_i[0]] ;# Bank  88 VCCO - VCC3V3   - IO_L8P_HDGC_88
set_property IOSTANDARD  LVCMOS33 [get_ports dip_switch_4bits_tri_i[0]] ;# Bank  88 VCCO - VCC3V3   - IO_L8P_HDGC_88

set_property PACKAGE_PIN A20      [get_ports uart2_pl_txd] ;# Bank  28 VCCO - VCC1V8   - IO_L21P_T3L_N4_AD8P_28
set_property IOSTANDARD  LVCMOS18 [get_ports uart2_pl_txd] ;# Bank  28 VCCO - VCC1V8   - IO_L21P_T3L_N4_AD8P_28
set_property PACKAGE_PIN C19      [get_ports uart2_pl_rxd] ;# Bank  28 VCCO - VCC1V8   - IO_L20N_T3L_N3_AD1N_28
set_property IOSTANDARD  LVCMOS18 [get_ports uart2_pl_rxd] ;# Bank  28 VCCO - VCC1V8   - IO_L20N_T3L_N3_AD1N_28

set_property PACKAGE_PIN AH18 [get_ports diff_clk_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports diff_clk_clk_p]
set_property PACKAGE_PIN AH17 [ get_ports diff_clk_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports diff_clk_clk_n]

set_property PACKAGE_PIN AG20 [get_ports {ddr4_sdram_dq[4]}]
set_property PACKAGE_PIN AF23 [get_ports {ddr4_sdram_dqs_t[0]}]
set_property PACKAGE_PIN AG23 [get_ports {ddr4_sdram_dqs_c[0]}]
set_property PACKAGE_PIN AE14 [get_ports {ddr4_sdram_dq[38]}]
set_property PACKAGE_PIN AD14 [get_ports {ddr4_sdram_dq[39]}]
set_property PACKAGE_PIN AG19 [get_ports {ddr4_sdram_dq[5]}]
set_property PACKAGE_PIN AC12 [get_ports {ddr4_sdram_dqs_t[4]}]
set_property PACKAGE_PIN AD12 [get_ports {ddr4_sdram_dqs_c[4]}]
set_property PACKAGE_PIN AF13 [get_ports {ddr4_sdram_dq[36]}]
set_property PACKAGE_PIN AH22 [get_ports {ddr4_sdram_dm_n[0]}]
set_property PACKAGE_PIN AG21 [get_ports {ddr4_sdram_dq[7]}]
set_property PACKAGE_PIN AH21 [get_ports {ddr4_sdram_dq[6]}]
set_property PACKAGE_PIN AE13 [get_ports {ddr4_sdram_dq[37]}]
set_property PACKAGE_PIN AB14 [get_ports ddr4_sdram_reset_n]
set_property PACKAGE_PIN AF11 [get_ports {ddr4_sdram_dm_n[4]}]
set_property PACKAGE_PIN AN19 [get_ports {ddr4_sdram_dq[30]}]
set_property PACKAGE_PIN AM19 [get_ports {ddr4_sdram_dq[31]}]
set_property PACKAGE_PIN AE15 [get_ports {ddr4_sdram_odt}]
set_property PACKAGE_PIN AP22 [get_ports {ddr4_sdram_dq[28]}]
set_property PACKAGE_PIN AP21 [get_ports {ddr4_sdram_dq[29]}]
set_property PACKAGE_PIN AP9 [get_ports {ddr4_sdram_dq[62]}]
set_property PACKAGE_PIN AN11 [get_ports {ddr4_sdram_dq[61]}]
set_property PACKAGE_PIN AP11 [get_ports {ddr4_sdram_dq[60]}]
set_property PACKAGE_PIN AC17 [get_ports ddr4_sdram_act_n]
set_property PACKAGE_PIN AM21 [get_ports {ddr4_sdram_dqs_t[3]}]
set_property PACKAGE_PIN AN21 [get_ports {ddr4_sdram_dqs_c[3]}]
set_property PACKAGE_PIN AP10 [get_ports {ddr4_sdram_dq[63]}]
set_property PACKAGE_PIN AN12 [get_ports {ddr4_sdram_dm_n[7]}]
set_property PACKAGE_PIN AD17 [get_ports {ddr4_sdram_cke}]
set_property PACKAGE_PIN AA15 [get_ports {ddr4_sdram_cs_n}]
set_property PACKAGE_PIN AP19 [get_ports {ddr4_sdram_dm_n[3]}]
set_property PACKAGE_PIN AN8 [get_ports {ddr4_sdram_dqs_c[7]}]
set_property PACKAGE_PIN AN9 [get_ports {ddr4_sdram_dqs_t[7]}]
set_property PACKAGE_PIN AL12 [get_ports {ddr4_sdram_dq[52]}]
set_property PACKAGE_PIN AC16 [get_ports {ddr4_sdram_bg[0]}]
set_property PACKAGE_PIN AL16 [get_ports {ddr4_sdram_ba[1]}]
set_property PACKAGE_PIN AK19 [get_ports {ddr4_sdram_dq[20]}]
set_property PACKAGE_PIN AL23 [get_ports {ddr4_sdram_dq[22]}]
set_property PACKAGE_PIN AL22 [get_ports {ddr4_sdram_dq[23]}]
set_property PACKAGE_PIN AL10 [get_ports {ddr4_sdram_dq[54]}]
set_property PACKAGE_PIN AK12 [get_ports {ddr4_sdram_dq[53]}]
set_property PACKAGE_PIN AK13 [get_ports {ddr4_sdram_dm_n[6]}]
set_property PACKAGE_PIN AA16 [get_ports {ddr4_sdram_adr[14]}]
set_property PACKAGE_PIN AJ19 [get_ports {ddr4_sdram_dq[21]}]
set_property PACKAGE_PIN AK22 [get_ports {ddr4_sdram_dqs_t[2]}]
set_property PACKAGE_PIN AK23 [get_ports {ddr4_sdram_dqs_c[2]}]
set_property PACKAGE_PIN AL11 [get_ports {ddr4_sdram_dq[55]}]
set_property PACKAGE_PIN AK18 [get_ports {ddr4_sdram_adr[13]}]
set_property PACKAGE_PIN AL18 [get_ports {ddr4_sdram_adr[12]}]
set_property PACKAGE_PIN AB16 [get_ports {ddr4_sdram_bg[1]}]
set_property PACKAGE_PIN AA14 [get_ports {ddr4_sdram_adr[15]}]
set_property PACKAGE_PIN AL20 [get_ports {ddr4_sdram_dm_n[2]}]
set_property PACKAGE_PIN AK8 [get_ports {ddr4_sdram_dqs_t[6]}]
set_property PACKAGE_PIN AL8 [get_ports {ddr4_sdram_dqs_c[6]}]
set_property PACKAGE_PIN AG13 [get_ports {ddr4_sdram_dq[45]}]
set_property PACKAGE_PIN AH13 [get_ports {ddr4_sdram_dq[44]}]
set_property PACKAGE_PIN AK15 [get_ports {ddr4_sdram_adr[11]}]
set_property PACKAGE_PIN AK14 [get_ports {ddr4_sdram_adr[10]}]
set_property PACKAGE_PIN AF16 [get_ports {ddr4_sdram_adr[4]}]
set_property PACKAGE_PIN AC19 [get_ports {ddr4_sdram_dq[14]}]
set_property PACKAGE_PIN AH11 [get_ports {ddr4_sdram_dq[47]}]
set_property PACKAGE_PIN AJ11 [get_ports {ddr4_sdram_dq[46]}]
set_property PACKAGE_PIN AH12 [get_ports {ddr4_sdram_dm_n[5]}]
set_property PACKAGE_PIN AJ17 [get_ports {ddr4_sdram_adr[9]}]
set_property PACKAGE_PIN AA18 [get_ports {ddr4_sdram_dqs_t[1]}]
set_property PACKAGE_PIN AB18 [get_ports {ddr4_sdram_dqs_c[1]}]
set_property PACKAGE_PIN AE20 [get_ports {ddr4_sdram_dq[12]}]
set_property PACKAGE_PIN AB19 [get_ports {ddr4_sdram_dq[15]}]
set_property PACKAGE_PIN AH9 [get_ports {ddr4_sdram_dqs_c[5]}]
set_property PACKAGE_PIN AG9 [get_ports {ddr4_sdram_dqs_t[5]}]
set_property PACKAGE_PIN AF15 [get_ports {ddr4_sdram_adr[3]}]
set_property PACKAGE_PIN AF17 [get_ports {ddr4_sdram_adr[7]}]
set_property PACKAGE_PIN AH14 [get_ports {ddr4_sdram_adr[6]}]
set_property PACKAGE_PIN AG14 [get_ports {ddr4_sdram_adr[1]}]
set_property PACKAGE_PIN AE18 [get_ports {ddr4_sdram_dm_n[1]}]
set_property PACKAGE_PIN AD20 [get_ports {ddr4_sdram_dq[13]}]
set_property PACKAGE_PIN AH16 [get_ports {ddr4_sdram_adr[0]}]
set_property PACKAGE_PIN AG15 [get_ports {ddr4_sdram_adr[2]}]
set_property PACKAGE_PIN AK17 [get_ports {ddr4_sdram_adr[8]}]
set_property PACKAGE_PIN AD15 [get_ports {ddr4_sdram_adr[16]}]
set_property PACKAGE_PIN AJ14 [get_ports {ddr4_sdram_adr[5]}]
set_property PACKAGE_PIN AL15 [get_ports {ddr4_sdram_ba[0]}]
set_property PACKAGE_PIN AF18 [get_ports {ddr4_sdram_ck_t}]
set_property PACKAGE_PIN AM11 [get_ports {ddr4_sdram_dq[59]}]
set_property PACKAGE_PIN AM10 [get_ports {ddr4_sdram_dq[58]}]
set_property PACKAGE_PIN AM9 [get_ports {ddr4_sdram_dq[57]}]
set_property PACKAGE_PIN AM8 [get_ports {ddr4_sdram_dq[56]}]
set_property PACKAGE_PIN AJ10 [get_ports {ddr4_sdram_dq[51]}]
set_property PACKAGE_PIN AK10 [get_ports {ddr4_sdram_dq[50]}]
set_property PACKAGE_PIN AJ9 [get_ports {ddr4_sdram_dq[49]}]
set_property PACKAGE_PIN AK9 [get_ports {ddr4_sdram_dq[48]}]
set_property PACKAGE_PIN AG11 [get_ports {ddr4_sdram_dq[43]}]
set_property PACKAGE_PIN AG10 [get_ports {ddr4_sdram_dq[42]}]
set_property PACKAGE_PIN AF8 [get_ports {ddr4_sdram_dq[41]}]
set_property PACKAGE_PIN AG8 [get_ports {ddr4_sdram_dq[40]}]
set_property PACKAGE_PIN AE12 [get_ports {ddr4_sdram_dq[35]}]
set_property PACKAGE_PIN AF12 [get_ports {ddr4_sdram_dq[34]}]
set_property PACKAGE_PIN AB13 [get_ports {ddr4_sdram_dq[33]}]
set_property PACKAGE_PIN AC13 [get_ports {ddr4_sdram_dq[32]}]
set_property PACKAGE_PIN AN22 [get_ports {ddr4_sdram_dq[27]}]
set_property PACKAGE_PIN AP23 [get_ports {ddr4_sdram_dq[26]}]
set_property PACKAGE_PIN AM23 [get_ports {ddr4_sdram_dq[25]}]
set_property PACKAGE_PIN AN23 [get_ports {ddr4_sdram_dq[24]}]
set_property PACKAGE_PIN AJ20 [get_ports {ddr4_sdram_dq[19]}]
set_property PACKAGE_PIN AK20 [get_ports {ddr4_sdram_dq[18]}]
set_property PACKAGE_PIN AJ21 [get_ports {ddr4_sdram_dq[17]}]
set_property PACKAGE_PIN AJ22 [get_ports {ddr4_sdram_dq[16]}]
set_property PACKAGE_PIN AC18 [get_ports {ddr4_sdram_dq[11]}]
set_property PACKAGE_PIN AD19 [get_ports {ddr4_sdram_dq[10]}]
set_property PACKAGE_PIN AA19 [get_ports {ddr4_sdram_dq[9]}]
set_property PACKAGE_PIN AA20 [get_ports {ddr4_sdram_dq[8]}]
set_property PACKAGE_PIN AF21 [get_ports {ddr4_sdram_dq[3]}]
set_property PACKAGE_PIN AF22 [get_ports {ddr4_sdram_dq[2]}]
set_property PACKAGE_PIN AE23 [get_ports {ddr4_sdram_dq[1]}]
set_property PACKAGE_PIN AE24 [get_ports {ddr4_sdram_dq[0]}]
